# Generate a local .env file for development using current WSL IP
# Writes SPRING_KAFKA_BOOTSTRAP_SERVERS and KAFKA_BOOTSTRAP_SERVERS to .env (repo root)
# This file is gitignored by default (.env) so it will remain local only.

# Get WSL IP (first non-empty address)
$ip = wsl hostname -I 2>$null | ForEach-Object { $_.Trim() } | Select-Object -First 1
if (-not $ip) {
    Write-Error "Could not determine WSL IP. Ensure WSL is running and 'hostname -I' works in your distro."
    exit 1
}

$kafka = "$ip:9092"
$envFile = Join-Path $PSScriptRoot ".env"

$content = @()
$content += "# Generated by setup-wsl-env.ps1 - safe to commit? No (it's gitignored)"
$content += "# Sets local Kafka bootstrap servers pointing at WSL-hosted broker"
$content += "SPRING_KAFKA_BOOTSTRAP_SERVERS=$kafka"
$content += "KAFKA_BOOTSTRAP_SERVERS=$kafka"

Set-Content -Path $envFile -Value $content -Encoding UTF8
Write-Host ".env created at $envFile with SPRING_KAFKA_BOOTSTRAP_SERVERS=$kafka"
Write-Host "Note: .env is ignored by git. Restart services to pick up the new value or run the app with --spring.config.import=optional:file:.env"